---
title: "case_study09"
format: html
editor: visual
---

------------------------------------------------------------------------

```{r}
# Load necessary library

library(sf)
library(tidyverse)
library(ggmap)
library(spData)
library(lubridate)
library(knitr)
data(world)

```

```{r}
# Download a csv from noaa with storm track information

dataurl="https://www.ncei.noaa.gov/data/international-best-track-archive-for-climate-stewardship-ibtracs/v04r01/access/csv/ibtracs.NA.list.v04r01.csv"

# Load us_states shapefile
storm_data <- read_csv(dataurl)
```

```{r}
# Create a new column with just the year
storm <- storm_data %>%
mutate(year = year(ISO_TIME)) %>%
# Filter to storms from 1950 to present
filter(year >= 1950) %>%
# Convert -999.0 to NA in all numeric columns
mutate_if(is.numeric, ~ifelse(. == -999.0, NA, .)) %>% 
  mutate(decade= floor(year /10) * 10) %>%
# Convert the data to a sf object
 st_as_sf(coords=c("LON","LAT"), crs=4326)
region <- st_bbox(storm)
```

```{r}
# Plot the world polygon layer 
ggplot() +
geom_sf(data = world, fill = "gray", color = "red") +
facet_wrap(~decade) +
  stat_bin2d(data=storm, aes(y=
  st_coordinates(storm)[,2], x=st_coordinates(storm)[,1]),bins=100)+
scale_fill_distiller(palette="YlOrRd", trans="log", direction=-1, breaks = c(1,10,100,1000))+
  coord_sf(ylim=region[c(2,4)], xlim=region[c(1,3)]) + theme_minimal() + 
labs(title = "storm by decade")
```

```{r}
#Create table of five states with most storms
us_states <- st_transform(us_states, crs = st_crs(storm))
#Rename column
us_states2 <- us_states %>%  
  select(state = NAME)
#spatial join between the storm database and the states object
storm_states<- st_join(storm, us_states2, join = st_intersects, left = FALSE)
#group_by(state) to group the next step by US state
top_states <- storm_states %>%   group_by(state) %>%   
  summarize(storms = length(unique(NAME))) %>% arrange(desc(storms)) %>%
  slice(1:5)
```

